# Generated by Django 3.1.8 on 2021-06-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210617_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='image_of_growth_stage',
        ),
    ]
