# Generated by Django 3.1.8 on 2021-10-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florapedia', '0006_auto_20211014_1646'),
        ('posts', '0004_image_of_growth_stage_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='florapedia.plant'),
        ),
    ]
