# Generated by Django 3.1.8 on 2021-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='days_without_water',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
