# Generated by Django 3.1.8 on 2021-10-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
        ('chat', '0003_discussion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
