# Generated by Django 3.1.8 on 2021-06-10 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('days_between_waterings', models.BigIntegerField()),
                ('article', models.TextField()),
                ('plant_genus', models.CharField(blank=True, max_length=50)),
                ('type_of_plant', models.CharField(blank=True, max_length=50)),
                ('plant_variety', models.CharField(blank=True, max_length=50)),
                ('growing_conditions', models.TextField()),
            ],
        ),
    ]
