# Generated by Django 3.1.8 on 2021-06-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florapedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_genus',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_variety',
            new_name='Genus',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='type_of_plant',
            new_name='Tribe',
        ),
    ]
