# Generated by Django 3.1.8 on 2021-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florapedia', '0002_auto_20210612_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='subcategory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plant',
            name='сategory',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
