# Generated by Django 3.1.8 on 2021-10-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florapedia', '0004_auto_20211014_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='сategory',
        ),
    ]
