# Generated by Django 3.1.8 on 2021-12-20 18:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('florapedia', '0006_auto_20211014_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
